import { test, expect, Page } from '@playwright/test';

async function login(page: Page) {
  await page.goto('/login');
  await page.fill('input[formControlName="email"]', 'admin@admin.com');
  await page.fill('input[formControlName="password"]', 'admin123');
  await page.click('button[type="submit"]');
  await expect(page).toHaveURL(/\/dashboard/);
}

test.describe('Notices Workflow', () => {
  test.beforeEach(async ({ page }) => {
    await login(page);
    await page.goto('/notices');
    await page.waitForLoadState('networkidle');
  });

  test('should create a new notice', async ({ page }) => {
    await page.click('button:has-text("Nuevo aviso")');
    
    await page.fill('input[formControlName="title"]', 'E2E Test Notice');
    await page.fill('textarea[formControlName="content"]', 'This is a test notice generated by Playwright.');
    
    const tenantSelect = page.locator('select[formControlName="tenantId"]');
    if (await tenantSelect.isVisible()) {
      await expect(tenantSelect.locator('option').nth(1)).toBeAttached();
      await tenantSelect.selectOption({ label: 'E2E Test Tenant' });
    }
    
    await page.click('button:has-text("Publicar aviso")');
    
    // Check for ANY toast indicating finish
    const toast = page.locator('.mcs-toast').first();
    await expect(toast).toBeVisible();
    await expect(toast).toContainText(/Aviso publicado/);
    
    // Verify entry in list
    await expect(page.locator('.mcs-list-row').filter({ hasText: 'E2E Test Notice' }).first()).toBeVisible();
  });
});
